[build]
builder = "nixpacks"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
source = "backend"

[services.build]
buildCommand = "npm ci && npm run build"

[services.deploy]
startCommand = "npm start"